In [178]:
import pandas as pd
import os
import sys
import warnings

warnings.filterwarnings('ignore')
current_dir = os.getcwd()
project_root = os.path.dirname(current_dir)
sys.path.insert(0, project_root)

import src.models_management as models_management
import src.ml_utils as ml_utils


%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [162]:
fase='III'
mm = models_management.ModelsManagement(fase)
df_vp = mm.prepare_data()
results = mm.train_models(fase)

1 - TRANSPORTE
  → Warning: Only 2 samples. Skipping outlier detection.
{'R2': -3.0, 'MAE': 4643975.471, 'RMSLE': 0.236, 'MAPE%': 23.791}
2.1 - INFORMACIÓN GEOGRÁFICA
  → Removed 1/10 outliers (10.0%) using ensemble
{'R2': 1.0, 'MAE': 199650.365, 'RMSLE': 0.096, 'MAPE%': 5.977}
2.2 - TRAZADO Y DISEÑO GEOMÉTRICO
  → Removed 5/50 outliers (10.0%) using ensemble
{'R2': 0.826, 'MAE': 2270169.486, 'RMSLE': 0.384, 'MAPE%': 22.302}
2.3 - SEGURIDAD VIAL
  → Removed 4/49 outliers (8.2%) using ensemble
{'R2': 0.792, 'MAE': 2511792.659, 'RMSLE': 0.494, 'MAPE%': 35.996}
2.4 - SISTEMAS INTELIGENTES
  → Removed 5/42 outliers (11.9%) using ensemble
{'R2': 0.851, 'MAE': 409025.912, 'RMSLE': 0.127, 'MAPE%': 4.59}
5 - TALUDES
  → Removed 7/44 outliers (15.9%) using ensemble
{'R2': 0.55, 'MAE': 4610935.437, 'RMSLE': 0.617, 'MAPE%': 21.407}
6 - PAVIMENTO
  → Removed 4/34 outliers (11.8%) using ensemble
{'R2': 0.241, 'MAE': 4531609.341, 'RMSLE': 0.652, 'MAPE%': 30.96}
7 - SOCAVACIÓN
  → Removed 5/50 outliers (10.0%) using ensemble
{'R2': 0.919, 'MAE': 3759520.045, 'RMSLE': 0.289, 'MAPE%': 19.058}
11 - PREDIAL
  → Warning: Only 4 samples. Skipping outlier detection.
{'R2': -0.404, 'MAE': 710990.123, 'RMSLE': 0.059, 'MAPE%': 3.892}
12 - IMPACTO AMBIENTAL
  → Warning: Only 2 samples. Skipping outlier detection.
{'R2': -3.0, 'MAE': 117199626.381, 'RMSLE': 4.275, 'MAPE%': 3593.536}
15 - OTROS - MANEJO DE REDES
  → Removed 4/34 outliers (11.8%) using ensemble
{'R2': 0.762, 'MAE': 3693765.648, 'RMSLE': 0.384, 'MAPE%': 20.865}
16 - DIRECCIÓN Y COORDINACIÓN
  → Removed 7/51 outliers (13.7%) using ensemble
{'R2': 0.95, 'MAE': 1516804.865, 'RMSLE': 0.137, 'MAPE%': 6.552}
  → Warning: Only 6 samples. Skipping outlier detection.
{'Model': 'Linear Regression (Log y)', 'R²': 0.875, 'MAE': 10116313.981, 'RMSE': 14989949.03, 'MAPE (%)': 10.369, 'Median AE': 6998272.538, 'Max Error': 33723872.728}
  → Warning: Only 7 samples. Skipping outlier detection.
{'Model': 'Model', 'R²': 0.931, 'MAE': 58727741.626, 'RMSE': 75610324.783, 'MAPE (%)': 39.004, 'Median AE': 35176571.996, 'Max Error': 132427513.227}
  → Warning: Only 6 samples. Skipping outlier detection.
{'Model': 'Model', 'R²': 0.911, 'MAE': 106072066.135, 'RMSE': 124728195.953, 'MAPE (%)': 36.056, 'Median AE': 86741275.295, 'Max Error': 233861419.752}

R² = 0.8340 | MAPE = 9.76%
  → Warning: Only 2 samples. Skipping outlier detection.
Warning: Only 2 samples available. Skipping cross-validation.
{'Model': 'Linear Regression', 'R²': 1.0, 'MAE': 0.0, 'RMSE': 0.0, 'MAPE (%)': 0.0, 'Median AE': 0.0, 'Max Error': 0.0}
  → Warning: Only 5 samples. Skipping outlier detection.
{'Model': 'Ridge', 'R²': 0.995, 'MAE': 1021210.421, 'RMSE': 1153118.706, 'MAPE (%)': 9.334, 'Median AE': 717706.14, 'Max Error': 1739110.278}

In [203]:
predictions = mm.predict_fase_III(
    codigo='',
    longitud_km=8.35,
    puentes_vehiculares_und=0,
    puentes_vehiculares_m2=0,
    puentes_peatonales_und=0,
    puentes_peatonales_m2=0.0,
    tuneles_und=0,
    tuneles_km=0.0,
    alcance='Rehabilitación',
    models=results
)

predictions

{'1 - TRANSPORTE': np.float64(18618090.870313264),
 '2.1 - INFORMACIÓN GEOGRÁFICA': np.float64(37891100.89439946),
 '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO': np.float64(23953110.623146273),
 '2.3 - SEGURIDAD VIAL': np.float64(18798283.340049006),
 '2.4 - SISTEMAS INTELIGENTES': np.float64(5465071.960027077),
 '5 - TALUDES': np.float64(22105992.098127816),
 '6 - PAVIMENTO': np.float64(9304521.247410001),
 '7 - SOCAVACIÓN': np.float64(62751142.99558687),
 '11 - PREDIAL': np.float64(16807112.315903552),
 '12 - IMPACTO AMBIENTAL': np.float64(14018200.941858964),
 '15 - OTROS - MANEJO DE REDES': np.float64(23472739.51593974),
 '16 - DIRECCIÓN Y COORDINACIÓN': np.float64(27724811.592005454),
 '3 - GEOLOGÍA': np.float64(19288341.202794045),
 '4 - SUELOS': np.float64(68203284.37192442),
 '8 - ESTRUCTURAS': np.float64(111134227.31300414),
 '9 - TÚNELES': np.float64(6336708.233323069),
 '10 - URBANISMO Y PAISAJISMO': np.float64(-1538910.2467023134),
 '13 - CANTIDADES': np.float64(7306543.9466367215)}

In [164]:
# df = df_vp[df_vp['2.2 - TRAZADO Y DISEÑO GEOMÉTRICO'] != 0]
predictor = 'LONGITUD KM'
target = '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO'
hue = 'ALCANCE'
# df = ml_utils.remove_outliers(df, target=target)
ml_utils.create_scatter_plot_with_regression(df_vp, predictor, target, hue)

In [201]:
result = results['2.2 - TRAZADO Y DISEÑO GEOMÉTRICO']
X = result['X']
y = result['y']
y_predicted = result['y_predicted']
model = result['model']
metrics = result['metrics']

# df_for_plot = df_vp[df_vp[target] != 0].copy()
# df_for_plot = ml_utils.remove_outliers(df_for_plot, target=target)

# ml_utils.predicted_plot(y, y_predicted, X, predictor, target, hue, df_vp)

output=X.copy()
output['y_predicted'] = y_predicted
output['y'] = y
output[output['ALCANCE'] == 'Rehabilitación']

    LONGITUD KM         ALCANCE  LONGITUD KM LOG   y_predicted             y
20         8.35  Rehabilitación         2.235376  2.395585e+07  2.405652e+07
21         8.60  Rehabilitación         2.261763  2.446147e+07  2.477678e+07
22         8.50  Rehabilitación         2.251292  2.430089e+07  2.448867e+07
26        15.00  Rehabilitación         2.772589  3.812318e+07  3.505602e+07
40         3.15  Rehabilitación         1.423108  1.136254e+07  7.361765e+06

In [199]:
df_vp[df_vp['ALCANCE'] == 'Mejoramiento'].loc[:, ['CÓDIGO', 'LONGITUD KM', 'ALCANCE', '2.2 - TRAZADO Y DISEÑO GEOMÉTRICO']]

     CÓDIGO  LONGITUD KM       ALCANCE  2.2 - TRAZADO Y DISEÑO GEOMÉTRICO
9   0266702        5.000  Mejoramiento                       6.311029e+06
12  0321501       50.900  Mejoramiento                       1.134648e+08
13  0321501        9.000  Mejoramiento                       2.006255e+07
14  0321501       21.000  Mejoramiento                       4.681261e+07
15  0321501       14.000  Mejoramiento                       3.120841e+07
16  0321501        6.560  Mejoramiento                       1.462337e+07
17  0321501       18.920  Mejoramiento                       4.217593e+07
18  0321501       14.520  Mejoramiento                       3.236758e+07
19  0321501        9.860  Mejoramiento                       2.197963e+07
23  0427901        5.000  Mejoramiento                       5.652966e+06
24  0552903       10.060  Mejoramiento                       2.561191e+07
25  0581301        5.243  Mejoramiento                       3.623384e+07

In [198]:
ml_utils.predicted_plot(y, y_predicted, X, predictor, target, hue, df_vp)